version: '3'
services:
    front:
        restart: always
        build: ./frontend/
        ports:
         - "4200:4200"
         - "49153:49153"
        volumes:
         - ./frontend:/app
        container_name: front
        hostname: front
        networks:
            tictactoe_net:
                ipv4_address: 172.28.0.3

    api:
        image: php
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/api
        command: php -S 0.0.0.0:8000 -t public
        env_file: ./backend/.env
        working_dir: /api
        container_name: api
        hostname: api
        networks:
            tictactoe_net:
                ipv4_address: 172.28.0.2
                aliases:
                    - api

networks:
    tictactoe_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/24
