version: '3'
services:
    front:
        image: alexsuch/angular-cli
        restart: always
        ports:
            - "4200:4200"
        volumes:
            - ./frontend:/front
        command: npm i && npm start
        working_dir: /front
        container_name: front
        hostname: tnm-front
        networks:
            tictactoe_net:
                ipv4_address: 172.28.0.3

    api:
        image: php
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/api
        env_file: ./backend/.env
        working_dir: /api
        command: composer install && php -S 0.0.0.0:8000 -t public
        container_name: api
        hostname: tnm-api
        networks:
            tictactoe_net:
                ipv4_address: 172.28.0.2
                aliases:
                    - api

networks:
    tictactoe_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/24
